apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/44smkn/argocd-sample
  destination:
    namespace: argocd
