apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/44smkn/argocd-sample
    targetRevision: master
    path: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
