apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/44smkn/argocd-sample
      passwordSecret:
        name: repo-secrets
        key: password
      usernameSecret:
        name: repo-secrets
        key: username
